# Generated by Django 4.2.5 on 2023-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='desc',
            field=models.TextField(),
        ),
    ]
