# Generated by Django 4.2.5 on 2023-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movieinfo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
